services:
  manpages:
    build:
      context: .
      dockerfile: Dockerfile.man
    image: mantis-terminal-manpages:ubuntu-22.04
    container_name: terminal_man
    restart: unless-stopped

  sftp:
    build:
      context: .
      dockerfile: Dockerfile.sftp
    image: mantis-terminal-sftp:latest
    container_name: terminal_sftp
    ports:
      - "8022:22"
    command: "sftpuser:password:1001:1001:upload"
    volumes:
      - scp_data:/home/sftpuser/upload
    restart: unless-stopped

volumes:
  scp_data:
